[sinks.msk_sink_%%SUFFIX%%]
type = "kafka"
inputs =  ["json_parser_%%SUFFIX%%"]   
bootstrap_servers = "%%AWS_MSK_BROKERS%%"
#key_field = "ip"
topic = "%%AWS_MSK_TOPIC%%"
compression = "none"
acknowledgements.enabled = true
  [sinks.msk_sink_%%SUFFIX%%.encoding]
  codec = "json"
  
